default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_scaffold_react_development

test:
  <<: *default
  database: rails_scaffold_react_test

production:
  <<: *default
  database: rails_scaffold_react_production
  username: rails_scaffold_react
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
